### ISSUE TITLE
is a repo alive ? and wich license ?

### ISSUE THREAD

**Issue by allustin** [vadv/1c-build-tmp#1]
we build docker images for postgresql with 1C extension on based on alpine image

i think what some portion of your code is useful for us. But i have some question

* @vadv - did you planed publish your images to docker-hub and maintains it ?
* wich license you prefered on you github code ?

**Comment by vadv** [comment]
Репо мертвое. Система живая. Тотже докер, правда перенесено все на waf.io
Выкладывать пока не хочу, не вижу смысла: тому, кому необходимо билдить под 20 систем, уже имеет свою систему сборки, или я ошибаюсь? :)
